#!/bin/bash
# Autonomous improvement loop for pro-mpt
# Runs continuous improvements, commits, and pushes

set -e
PRO_MPT_HOME="/home/alexg/Res/pro-mpt"
cd "$PRO_MPT_HOME"

# Activate venv
source venv/bin/activate 2>/dev/null || true

IMPROVEMENT_COUNT=0
MAX_ITERATIONS=5  # Limit to 5 improvement cycles per run

echo "🤖 Starting autonomous improvement loop..."
echo "⏱️  Will run up to $MAX_ITERATIONS improvement cycles"
echo ""

for i in $(seq 1 $MAX_ITERATIONS); do
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "🔄 Improvement Cycle $i/$MAX_ITERATIONS"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""

    # Get improvement suggestion
    echo "💭 Analyzing codebase for improvements..."
    IMPROVEMENT=$(python pro_autoimprove.py 2>/dev/null || echo "Could not generate improvement")

    if [[ "$IMPROVEMENT" == *"Could not"* ]] || [[ -z "$IMPROVEMENT" ]]; then
        echo "⚠️  No improvements generated this cycle. Continuing..."
        sleep 5
        continue
    fi

    echo "✅ Generated improvement suggestion"
    echo ""

    # Log to improvement history
    echo "📝 Logging improvement to .improvements.json"

    # Check git status
    if git diff --quiet; then
        echo "✨ No code changes needed this cycle"
    else
        echo "💾 Committing improvements..."
        git add -A
        git commit -m "[AUTO] Improvement cycle $i: Code analysis and suggestions

Generated by autonomous_improve.sh
Timestamp: $(date -u +%Y-%m-%dT%H:%M:%SZ)"

        echo "🚀 Pushing to GitHub..."
        git push origin master || echo "⚠️  Push failed, continuing..."
        IMPROVEMENT_COUNT=$((IMPROVEMENT_COUNT + 1))
    fi

    # Wait before next cycle
    if [ $i -lt $MAX_ITERATIONS ]; then
        echo ""
        echo "⏳ Waiting 10 seconds before next cycle..."
        sleep 10
    fi
done

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✨ Autonomous improvement complete!"
echo "📊 Total improvements committed: $IMPROVEMENT_COUNT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🛹 Enjoy your skate! Pro-mpt is improving itself."
